Models/Deposit.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using MVC_ASP.NET_Core_Learn.Data.Enums;


namespace MVC_ASP.NET_Core_Learn.Models
{
    public class Deposit
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }                          // Айді
        public string Title { get; set; }                    // Назва депозиту
        public string ShortDescription { get; set; }         // Короткий опис депозиту
        public bool Replenishment { get; set; }              // Поповнення
        public InterestPayment InterestPayment { get; set; }       // Виплата процентів
        public List<DepositTerm> Terms { get; set; }   // Термін депозиту
        public double? InterestRateNoEarlyClosure { get; set; } // Ставка без дострокового закриття
        public double? InterestRateEarlyClosure { get; set; }   // Ставка з достроковим закриттям
	}
}

Controllers/DepositController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVC_ASP.NET_Core_Learn.Data.Interfaces;
using MVC_ASP.NET_Core_Learn.Models;
using MVC_ASP.NET_Core_Learn.ViewModels;

namespace MVC_ASP.NET_Core_Learn.Controllers
{
    /// <summary>
    /// Контролер для управління шаблонами депозитів.
    /// </summary>
    [Authorize]
    public class DepositController : Controller
	{
		private readonly IDepositRepository _depositRepository;

        public DepositController(IDepositRepository depositRepository)
		{
			_depositRepository = depositRepository;
        }

        [HttpGet("Open")]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
		{
			IEnumerable<Deposit> deposits = await _depositRepository.GetAll();

			return View(deposits);
		}

        public IActionResult Create()
        {
            var editVM = new EditDepositViewModel();

            return View(editVM);
        }

        [HttpPost]
        public IActionResult Create(EditDepositViewModel depositVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit deposit");
                return View(depositVM);
            }

            if (depositVM.Terms.Any(t => t.NumberMonths < 1))
            {
                TempData["Error"] = "Failed to add. Terms must be greatest than 0";
                return View("Create", depositVM);
            }

            var deposit = new Deposit()
            {
                Title = depositVM.Title,
                ShortDescription = depositVM.ShortDescription,
                Replenishment = depositVM.Replenishment,
                InterestPayment = depositVM.InterestRate,
                Terms = depositVM.Terms,
                InterestRateEarlyClosure = depositVM.InterestRateEarlyClosure,
                InterestRateNoEarlyClosure = depositVM.InterestRateNoEarlyClosure,
            };

            _depositRepository.Add(deposit);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var deposit = await _depositRepository.GetByIdAsync(id);
            if (deposit == null) return View("Error");
            var depositVM = new EditDepositViewModel()
            {
                Id = id,
                Title = deposit.Title,
                ShortDescription = deposit.ShortDescription,
                Replenishment = deposit.Replenishment,
                InterestRate = deposit.InterestPayment,
                Terms = deposit.Terms,
                InterestRateEarlyClosure = deposit.InterestRateEarlyClosure,
                InterestRateNoEarlyClosure = deposit.InterestRateNoEarlyClosure,
            };

            return View(depositVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditDepositViewModel depositVM)
		{
			if (!ModelState.IsValid)
			{
				ModelState.AddModelError("", "Failed to edit deposit");
				return View("Edit", depositVM);
			}

			if(depositVM.Terms.Any(t => t.NumberMonths < 1))
			{
                TempData["Error"] = "Failed to edit. Terms must be greatest than 0";
                return View("Edit", depositVM);
            }

			var userDeposit = await _depositRepository.GetByIdAsyncNoTraking(id);

			if (userDeposit != null)
			{
				var deposit = new Deposit()
				{
					Id = id,
					Title = depositVM.Title,
					ShortDescription = depositVM.ShortDescription,
					Replenishment = depositVM.Replenishment,
					InterestPayment = depositVM.InterestRate,
					Terms = depositVM.Terms,
					InterestRateEarlyClosure = depositVM.InterestRateEarlyClosure,
					InterestRateNoEarlyClosure = depositVM.InterestRateNoEarlyClosure,
				};

				_depositRepository.Update(deposit);
				return RedirectToAction("Index");
			}
			else
			{
				return View(depositVM);
			}
		}

		public async Task<IActionResult> Delete(int id)
		{
			var userDeposit = await _depositRepository.GetByIdAsync(id);

			if (userDeposit != null)
			{
				_depositRepository.Delete(userDeposit);
			}

			return RedirectToAction("Index");
		}
    }
}

Views/Deposit/Create.cshtml
@using MVC_ASP.NET_Core_Learn.Data.Enums
@using MVC_ASP.NET_Core_Learn.Data.Extensions
@model MVC_ASP.NET_Core_Learn.ViewModels.EditDepositViewModel

@{
    // Отримуємо всі значення перерахування InterestPayment
    var enumValues = Enum.GetValues(typeof(InterestPayment)).Cast<InterestPayment>();

    // Перетворюємо кожне значення перерахування на об'єкт SelectListItem
    var interestRates = enumValues.Select(e => new SelectListItem
    {
        Value = e.ToString(),
        Text = e.GetDescription()
    });
}


<div id="main" class="wrapper style1">
    <div class="container">
        @using (Html.BeginForm("Create", "Deposit", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            @if (TempData["Error"] != null)
            {
                <br />
                <div class="col-md-12 alert alert-danger">
                    <span class="text-danger fw-bold">@TempData["Error"] </span>
                </div>
            }
            <div class="form-group">
                @Html.LabelFor(model => model.Title)
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.ShortDescription)
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control", placeholder = "ShortDescription" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                <input asp-for="Replenishment" class="form-control">
                <label asp-for="Replenishment"></label>
                <span asp-validation-for="Replenishment" class="text-danger"></span>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.InterestRate)
                @Html.DropDownListFor(model => model.InterestRate, interestRates, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InterestRate, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Terms)
                <div id="term-list-container">
                    <!-- Тут відображатимуться поля для введення термінів -->
                    @for (int i = 0; i < Model?.Terms?.Count; i++)
                    {
                        <div>
                            @Html.HiddenFor(model => model.Terms[i].Id)
                            @Html.TextBoxFor(model => model.Terms[i].NumberMonths, new { @class = "term-input", type = "number" })
                        </div>
                    }
                    @* @Html.ValidationMessageFor(model => model.Terms, "", new { @class = "text-danger" }) *@

                </div>
            </div>
            <button type="button" class="btn btn-success" id="add-term-button">+</button>
            <button type="button" class="btn btn-danger" id="remove-term-button">-</button>

            <div class="form-group">
                @Html.LabelFor(model => model.InterestRateNoEarlyClosure)
                @Html.EditorFor(model => model.InterestRateNoEarlyClosure, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InterestRateNoEarlyClosure, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.InterestRateEarlyClosure)
                @Html.EditorFor(model => model.InterestRateEarlyClosure, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InterestRateEarlyClosure, "", new { @class = "text-danger" })
            </div>

            <button type="submit" class="button primary">Submit</button>
        }
    </div>
</div>

<!-- Шаблон текстового поля -->
<template id="input-template">
    <div class="form-group">
        <input type="number" class="term-input" name="terms[newIndex].NumberMonths" />
    </div>
</template>

<!-- Скрипт для додавання та видалення термінів -->
<script src="/js/term-interactions.js"></script>

Views/Deposit/Detail.cshtml
@using MVC_ASP.NET_Core_Learn.ViewModels
@model UserDepositViewModel


<div id="main" class="wrapper style1" style="display: block; justify-content: center; align-items: center; flex-direction: column;">
    <header class="major">
        <h2>Оформлення депозиту</h2>
    </header>
    <div class="container d-flex justify-content-center" style="width:50%">
        <form asp-action="SubscribeUserToDeposit" method="post" onsubmit="updateTermsJson()">
            <!-- Передеча необхідних данних для коректного відображення форми (прихована для користувача) -->
            <div>
                <input type="hidden" asp-for="DepositId" />
                <input type="hidden" asp-for="Title" />
                <input type="hidden" asp-for="InterestRateEarlyClosure" />
                <input type="hidden" asp-for="InterestRateNoEarlyClosure" />
                @for (int i = 0; i < Model.Terms.Count; i++)
                {
                    <input type="hidden" name="Terms[@i].Id" value="@(Model.Terms[i].Id)" />
                    <input type="hidden" name="Terms[@i].NumberMonths" value="@(Model.Terms[i].NumberMonths)" />
                }
            </div>

            <!-- Перший етап -->
            <section id="stage1" class="stage">
                <h3>Крок 1: Основна інформація</h3>

                <!-- Вибір ставки -->
                <h4>Выберите ставку и условия договора:</h4>
                <span asp-validation-for="InterestRate" class="text-danger"></span>
                @if (Model.InterestRateNoEarlyClosure != null)
                {
                    <div>
                        <input type="radio" id="depositNoEarlyClosure" name="SelectedInterestRate"
                                value="@Model.InterestRateNoEarlyClosure" onchange="updateSelectedRate(this)" />
                        <label for="depositNoEarlyClosure">@Model.InterestRateNoEarlyClosure% річних<br /> для вклада без досрочного розірвання</label>
                    </div>
                }
                @if (Model.InterestRateEarlyClosure != null)
                {
                    <div>
                        <input type="radio" id="depositEarlyClosure" name="SelectedInterestRate"
                                value="@Model.InterestRateEarlyClosure" onchange="updateSelectedRate(this)" />
                        <label for="depositEarlyClosure">@Model.InterestRateEarlyClosure% річних<br /> для вклада з досрочним розірванням</label>
                    </div>
                }

                <!-- Данні сформовані на виборі ставки-->
                <input type="hidden" asp-for="InterestRate"/>
                <input type="hidden" asp-for="IsEarlyClosureAllowed"/>
            </section>


            <!-- Другий етап -->
            <section id="stage2" class="stage" hidden>
                <h3>Крок 2: Додаткова інформація</h3>

                <!-- Поточний тариф та процентна ставка-->
                <div>
                    <b>Назва:</b> @Model.Title
                </div>
                @* <div>
                    <b>Ставка:</b> @Model.InterestRate
                </div> *@
                <br />

                <!-- Вибір термінів депозиту -->
                <div class="form-group">
                    <h4>Виберіть строк: </h4>
                    <span asp-validation-for="SelectedTerm" class="text-danger"></span>
                    <div>
                        @foreach (var term in Model.Terms)
                        {
                            <div class="form-check-inline">
                                <input class="form-check-input" type="radio" name="selectedTerm" id="inlineRadio@(term.Id)" value="@term.NumberMonths">
                                <label class="form-check-label" for="inlineRadio@(term.Id)">@term.NumberMonths</label>
                            </div>
                        }
                    </div>
                </div>
                <br />

                <!-- Введення суми депозиту -->
                <div style="margin: 0px 0px 20px 0;">
                    <h4>
                        <label asp-for="Amount"></label>
                    </h4>
                    <span asp-validation-for="Amount" class="text-danger"></span>
                    <div class="row">
                        <div class="col-8">
                            <input asp-for="Amount" />
                        </div>
                        <div class="col" style="display: flex; align-items: center; padding: 10px">
                            <span>UAH</span>
                        </div>
                    </div>
                </div>
            </section>

            <section id="stage3" class="stage d-flex flex-column align-items-center" hidden>
                <h3>Крок 3: Підтвердження</h3>
                <button class="button primary" type="submit" id="submitButton">Отправить</button>
            </section>


        </form>
    </div>
    <!-- Навігаційні кнопки -->
    <div class="d-flex justify-content-center mt-3">
        <p class="button" onclick="prevStage()" style="margin-right: 10px;">Назад</p>
        <p class="button" onclick="nextStage()">Далее</p>
    </div>
</div>

<script>
    function prevStage() {
        var stages = document.querySelectorAll('.stage'); // Знаходимо всі етапи
        for (var i = 0; i < stages.length; i++) {
            if (!stages[i].hasAttribute('hidden')) { // Знаходимо поточний етап
                if (i === 0) return; // Якщо поточний етап - перший, виходимо з функції
                stages[i].setAttribute('hidden', ''); // Приховуємо поточний етап
                stages[i - 1].removeAttribute('hidden'); // Показуємо попередній етап
                break;
            }
        }
    }

    function nextStage() {
        var stages = document.querySelectorAll('.stage'); // Знаходимо всі етапи
        for (var i = 0; i < stages.length; i++) {
            if (!stages[i].hasAttribute('hidden')) { // Знаходимо поточний етап
                if (i === stages.length - 1) return; // Якщо поточний етап - останній, виходимо з функції
                stages[i].setAttribute('hidden', ''); // Приховуємо поточний етап
                stages[i + 1].removeAttribute('hidden'); // Показуємо наступний етап
                break;
            }
        }
    }

    function updateSelectedRate(radioButton) {
        var selectedInterestRate = radioButton.value; // Отримати значення вибраної ставки
        var isEarlyClosure = radioButton.id.includes("depositEarlyClosure"); // Перевірити, чи є опція з досрочним розірванням

        // Встановити значення в моделі
        document.getElementById("InterestRate").value = selectedInterestRate;
        document.getElementById("IsEarlyClosureAllowed").value = isEarlyClosure;
    }
</script>


@* 
    <!-- Вибір терміну(RadioButton) -->
    <div>
    @foreach (var term in Model.Terms)
    {
    <input type="radio" id="term@(term.Id)" name="SelectedTerm" value="@term.Id" />
    <label for="term@(term.Id)">@term.NumberMonths</label>
    }
    </div>


    <!-- Выбор срока -->
                     <div>
    <label asp-for="SelectedTermId"></label>
    <select asp-for="SelectedTermId" asp-items="@(new SelectList(Model.Terms, "Id", "NumberMonths"))">
    <option value="">-- Select Term --</option>
    </select>
    </div> 


    <!-- TODO: Переделать под нормальное отображение -->
    <!-- Выбранная ставка -->
    <div id="selectedRateContainer" ">
    <h4>Выбранная ставка:</h4>
    <p id="selectedRate"></p>
    </div>

<script>

    document.addEventListener('DOMContentLoaded', function () {
        // Обработчик для выбора ставки
        document.querySelectorAll('input[name="SelectedInterestRate"]').forEach(radio => {
            radio.addEventListener('change', function () {
                document.getElementById('selectedRate').textContent = this.value + '% річних'; // Отображаем выбранную ставку
                document.getElementById('selectedRateContainer').style.display = 'block'; // Показываем контейнер с выбранной ставкой
            });
        });
    });
</script> *@

Views/Deposit/Edit.cshtml
@using MVC_ASP.NET_Core_Learn.Data.Enums
@using MVC_ASP.NET_Core_Learn.ViewModels
@model EditDepositViewModel

@{
    var interestRateOptions = new List<SelectListItem>
    {
        new SelectListItem { Value = InterestPayment.WhenReturning.ToString(), Text = "При повернені" },
        new SelectListItem { Value = InterestPayment.Monthly.ToString(), Text = "Щомісяця" },
        new SelectListItem { Value = InterestPayment.Yearly.ToString(), Text = "Щороку" },
        // Додайте інші варіанти, які вам потрібно відобразити
    };
}

<div id="main" class="wrapper style1">
    <div class="container">
        @using (Html.BeginForm("Edit", "Deposit", FormMethod.Post))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Title)
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ShortDescription)
                @Html.TextAreaFor(model => model.ShortDescription, new { @class = "form-control", rows = 4 })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                <div class="form-check">
                    @Html.CheckBoxFor(model => model.Replenishment, new { @class = "form-check-input" })
                    @Html.LabelFor(model => model.Replenishment, new { @class = "form-check-label" })
                </div>
                @Html.ValidationMessageFor(model => model.Replenishment, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.InterestRate)
                @Html.DropDownListFor(model => model.InterestRate, new SelectList(interestRateOptions, "Value", "Text"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.InterestRate, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Terms)
                @for (int i = 0; i < Model?.Terms.Count; i++)
                {
                    <div>
                        @Html.HiddenFor(model => model.Terms[i].Id)
                        @Html.TextBoxFor(model => model.Terms[i].NumberMonths, new { @class = "form-control" })
                    </div>
                }
                @Html.ValidationMessageFor(model => model.Terms, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.InterestRateNoEarlyClosure)
                @Html.EditorFor(model => model.InterestRateNoEarlyClosure, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InterestRateNoEarlyClosure, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.InterestRateEarlyClosure)
                @Html.EditorFor(model => model.InterestRateEarlyClosure, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InterestRateEarlyClosure, "", new { @class = "text-danger" })
            </div>

            <div style="text-align: center; margin-top: 15px;">
                <button type="submit" class="button">Зберегти</button>
            </div>
        }
    </div>
</div>

Views/Deposit/Index.cshtml
@using MVC_ASP.NET_Core_Learn.Data.Extensions
@model IEnumerable<Deposit>

@{
	ViewData["Title"] = "Пропозиції";
}

@{
	// TODO: Скоріш всього ці функції варто перенести в модель Deposit
	string ComposeReplenishmentString(bool replenishment)
	{
		return replenishment ? "Так" : "Ні";
	}

	// Формує строку термінів
	string ComposeTermString(Deposit deposit)
	{
		var terms = deposit.Terms.Select(t => t.NumberMonths.ToString());

		if (terms.Count() == 1)
			return terms.First();

		var delimiter = terms.Count() == 2 ? " та " : ", ";
		return string.Join(delimiter, terms);
	}

	string ComposeRateClosureString(double? rateClosure)
	{
		if (rateClosure.HasValue)
		{
			return rateClosure.Value.ToString() + "%";
		}
		else
		{
			return "-";
		}
	}
}


<div id="main" class="wrapper style1">
	<div class="container">
		<header class="major">
			<h2> Оберіть бажаний депозит</h2>
		</header>

		@* TODO: Додати модельне вікно для видалення, видиме тільки адміну*@
		@* <!-- Модальне вікно для підтвердження видалення -->
		<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" hidden>
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4 class="modal-title" id="myModalLabel">Modal Title</h4>
					</div>
					<div class="modal-body">
						<p>Modal Content Goes Here</p>
					</div>
					<div class="modal-footer">
						<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
						<button type="button" class="btn btn-primary">Save changes</button>
					</div>
				</div>
			</div>
		</div> *@

		<div class="table-wrapper">
			<table class="alt">
				<thead>
					<tr style="font-size: 18pt">
						@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
						{
							<td rowspan="2" class="text-center">
								<p class="mb-3">Взаємодія з шаблонами</p>
								<a asp-controller="Deposit" asp-action="Create" class="btn btn-outline-success btn-lg">Додати шаблон</a>
							</td>
						}
						<th rowspan="2">Назва</th>
						<th rowspan="2">Поповнення</th>
						<th rowspan="2">Виплата процентів</th>
						<th rowspan="2">Термін, міс</th>
						<th colspan="2">Ставка річних</th>
					</tr>
					<tr style="font-size: 12pt">
						<th>Без дострокового закриття</th>
						<th>З достроковим закриттям</th>
					</tr>
				</thead>
				<tbody>
					@foreach (var item in Model)
					{
						<tr>
							@if (User.Identity.IsAuthenticated && User.IsInRole("admin"))
							{
								<td class="admin-td text-center align-middle">
									<a asp-controller="Deposit" asp-action="Edit" asp-route-id="@item.Id" class="button primary small">Змінити</a>
									<a asp-controller="Deposit" asp-action="Delete" asp-route-id="@item.Id" class="button primary small">Видалити</a>
								</td>
							}
							<td class="text-start">
								<b> @item.Title</b><br />
								@item.ShortDescription
							</td>
							<td>@ComposeReplenishmentString(item.Replenishment)</td>
							<td>@item.InterestPayment.GetDescription()</td>
							<td>@ComposeTermString(item)</td>
							<td>@ComposeRateClosureString(item.InterestRateNoEarlyClosure)</td>
							<td>@ComposeRateClosureString(item.InterestRateEarlyClosure)</td>
							<td class="align-middle">
								<a asp-controller="UserDeposit" asp-action="OrderForm" asp-route-depositId="@item.Id" class="button small">Оформити</a>
							</td>
						</tr>
					}
				</tbody>
			</table>
		</div>
	</div>
</div>

@* <script>
	$(document).ready(function () {
		$('#deleteButton').click(function () {
			$('#myModal').removeAttr('hidden').modal('show');
		});
	});
</script> *@

Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/css/fontawesome-all.min.css">
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.min.css" />
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-reboot.min.css" />
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true"/> 
<noscript><link rel="stylesheet" href="~/css/noscript.css" /></noscript>

Views/Shared/FooterPartial.cshtml
<!-- Footer -->
<footer id="footer">
	<ul class="icons">
		<li><a href="#" class="icon brands alt fa-twitter"><span class="label">Twitter</span></a></li>
		<li><a href="#" class="icon brands alt fa-facebook-f"><span class="label">Facebook</span></a></li>
		<li><a href="#" class="icon brands alt fa-linkedin-in"><span class="label">LinkedIn</span></a></li>
		<li><a href="#" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
		<li><a href="https://github.com/XEducat" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
		<li><a href="#" class="icon solid alt fa-envelope"><span class="label">Email</span></a></li>
	</ul>
	<ul class="copyright">
		<li>&copy; Untitled. All rights reserved.</li>
		<li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
	</ul>
</footer>

Views/Shared/HeaderPartial.cshtml
 <!-- Header -->
<header id="header">
    <h1 id="logo"><a asp-controller="Home" asp-action="Index">Home</a></h1>
    <nav id="nav">
        <ul>
            <li>
                <a href="#">Layouts</a>
                <ul>
                    <li><a href="left-sidebar.html">Left Sidebar</a></li>
                    <li><a href="right-sidebar.html">Right Sidebar</a></li>
                    <li><a href="no-sidebar.html">No Sidebar</a></li>
                    <li>
                        <a href="#">Submenu</a>
                        <ul>
                            <li><a href="#">Option 1</a></li>
                            <li><a href="#">Option 2</a></li>
                            <li><a href="#">Option 3</a></li>
                            <li><a href="#">Option 4</a></li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li><a asp-controller="Deposit" asp-action="Index">Deposits</a></li>
            @if (User.Identity.IsAuthenticated)
            {
                <li><a asp-controller="UserDeposit" asp-action="All">Wallet</a></li>
                <li><a asp-controller="User" asp-action="About" class="button">Profile</a></li>
            }
            else
            {
                <li><a asp-controller="Account" asp-action="Login" class="button">Sign In</a></li>
            }
        </ul>
    </nav>
</header>

Views/Shared/MetatagsPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />


@if(ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title> ASP.NET Core Learn</title>
}

Views/Shared/ScriptsPartial.cshtml
 <!-- Scripts -->
<script src="/js/jquery.min.js"></script>
<script src="/js/jquery.scrolly.min.js"></script>
<script src="/js/jquery.dropotron.min.js"></script>
<script src="/js/jquery.scrollex.min.js"></script>
<script src="/js/browser.min.js"></script>
<script src="/js/breakpoints.min.js"></script>
<script src="/js/util.js"></script>
<script src="/js/main.js"></script>
<script src="/js/myscripts.js"></script>
<script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
<script src="/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>

@*     
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> *@