ASP.NET Core Learn.Web/Controllers/DepositTemplateController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MVC_ASP.NET_Core_Learn.Data.Interfaces;
using MVC_ASP.NET_Core_Learn.Models;
using MVC_ASP.NET_Core_Learn.ViewModels;

namespace MVC_ASP.NET_Core_Learn.Controllers
{
    /// <summary>
    /// Контролер для управління шаблонами депозитів.
    /// </summary>
    [Authorize]
    public class DepositTemplateController : Controller
	{
		private readonly IDepositRepository _depositRepository;

        public DepositTemplateController(IDepositRepository depositRepository)
		{
			_depositRepository = depositRepository;
        }

        [HttpGet("Open")]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
		{
			IEnumerable<DepositTemplate> deposits = await _depositRepository.GetAll();

			return View(deposits);
		}

        public IActionResult Create()
        {
            var editVM = new EditDepositViewModel();

            return View(editVM);
        }

        [HttpPost]
        public IActionResult Create(EditDepositViewModel depositVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit deposit");
                return View(depositVM);
            }

            if (depositVM.Terms.Any(t => t.NumberMonths < 1))
            {
                TempData["Error"] = "Failed to add. Terms must be greatest than 0";
                return View("Create", depositVM);
            }

            var deposit = new DepositTemplate()
            {
                Title = depositVM.Title,
                ShortDescription = depositVM.ShortDescription,
                Replenishment = depositVM.Replenishment,
                InterestPayment = depositVM.InterestRate,
                Terms = depositVM.Terms,
                InterestRateEarlyClosure = depositVM.InterestRateEarlyClosure,
                InterestRateNoEarlyClosure = depositVM.InterestRateNoEarlyClosure,
            };

            _depositRepository.Add(deposit);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            var deposit = await _depositRepository.GetByIdAsync(id);
            if (deposit == null) return View("Error");
            var depositVM = new EditDepositViewModel()
            {
                Id = id,
                Title = deposit.Title,
                ShortDescription = deposit.ShortDescription,
                Replenishment = deposit.Replenishment,
                InterestRate = deposit.InterestPayment,
                Terms = deposit.Terms,
                InterestRateEarlyClosure = deposit.InterestRateEarlyClosure,
                InterestRateNoEarlyClosure = deposit.InterestRateNoEarlyClosure,
            };

            return View(depositVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, EditDepositViewModel depositVM)
		{
			if (!ModelState.IsValid)
			{
				ModelState.AddModelError("", "Failed to edit deposit");
				return View("Edit", depositVM);
			}

			if(depositVM.Terms.Any(t => t.NumberMonths < 1))
			{
                TempData["Error"] = "Failed to edit. Terms must be greatest than 0";
                return View("Edit", depositVM);
            }

			var userDeposit = await _depositRepository.GetByIdAsyncNoTraking(id);

			if (userDeposit != null)
			{
				var deposit = new DepositTemplate()
				{
					Id = id,
					Title = depositVM.Title,
					ShortDescription = depositVM.ShortDescription,
					Replenishment = depositVM.Replenishment,
					InterestPayment = depositVM.InterestRate,
					Terms = depositVM.Terms,
					InterestRateEarlyClosure = depositVM.InterestRateEarlyClosure,
					InterestRateNoEarlyClosure = depositVM.InterestRateNoEarlyClosure,
				};

				_depositRepository.Update(deposit);
				return RedirectToAction("Index");
			}
			else
			{
				return View(depositVM);
			}
		}

		public async Task<IActionResult> Delete(int id)
		{
			var userDeposit = await _depositRepository.GetByIdAsync(id);

			if (userDeposit != null)
			{
				_depositRepository.Delete(userDeposit);
			}

			return RedirectToAction("Index");
		}
    }
}

ASP.NET Core Learn.Web/Views/Shared/Partials/_CssPartial.cshtml
<link rel="stylesheet" href="~/css/fontawesome-all.min.css">
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.min.css" />
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-reboot.min.css" />
<link rel="stylesheet" href="~/css/main.css" asp-append-version="true"/> 
<noscript><link rel="stylesheet" href="~/css/noscript.css" /></noscript>

ASP.NET Core Learn.Web/Views/Shared/Partials/_FooterPartial.cshtml
<!-- Footer -->
<footer id="footer">
	<ul class="icons">
		<li><a href="/Twitter" class="icon brands alt fa-twitter"><span class="label">Twitter</span></a></li>
		<li><a href="/Facebook" class="icon brands alt fa-facebook-f"><span class="label">Facebook</span></a></li>
		<li><a href="/LinkedIn" class="icon brands alt fa-linkedin-in"><span class="label">LinkedIn</span></a></li>
		<li><a href="/Instagram" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
		<li><a href="https://github.com/XEducat" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
		<li><a href="https://t.me/StashSpot_bot" class="icon brands alt fa-telegram"><span class="label">Telegram Bot</span></a></li>
	</ul>
	<ul class="copyright">
		<li>&copy; Untitled. All rights reserved.</li>
	</ul>
</footer>

ASP.NET Core Learn.Web/Views/Shared/Partials/_HeaderPartial.cshtml
 <!-- Header Partial -->
<header id="header">
    <h1 id="logo">
        <a asp-controller="Home" asp-action="Index">StashSpot</a>
        <img src="/images/icons/StashSpotIcon.svg" alt="StashSpotIcon" />
    </h1>
    <nav id="nav">
        <ul>
@*             <li>
                <a href="#">Layouts</a>
                <ul>
                    <li><a href="left-sidebar.html">Left Sidebar</a></li>
                    <li><a href="right-sidebar.html">Right Sidebar</a></li>
                    <li><a href="no-sidebar.html">No Sidebar</a></li>
                    <li>
                        <a href="#">Submenu</a>
                        <ul>
                            <li><a href="#">Option 1</a></li>
                            <li><a href="#">Option 2</a></li>
                            <li><a href="#">Option 3</a></li>
                            <li><a href="#">Option 4</a></li>
                        </ul>
                    </li>
                </ul>
            </li> *@
            <li><a asp-controller="DepositTemplate" asp-action="Index">Депозити</a></li>
            @if (User.Identity.IsAuthenticated)
            {
                <li><a asp-controller="UserDeposit" asp-action="All">Мої вкладення</a></li>
                <li>
                    <a asp-controller="User" asp-action="About" class="button">Профіль</a>
                </li>
            }
            else
            {
                <li><a asp-controller="Account" asp-action="Login" class="button">Ввійти</a></li>
            }
        </ul>
    </nav>
</header>

ASP.NET Core Learn.Web/Views/Shared/Partials/_MetatagsPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />


@if(ViewBag.Title != null)
{
    <title>@ViewBag.Title</title>
}
else
{
    <title> ASP.NET Core Learn</title>
}

ASP.NET Core Learn.Web/Views/Shared/Partials/_ScriptsPartial.cshtml
 <!-- Scripts -->
<script src="/js/jquery.min.js"></script>
<script src="/js/jquery.scrolly.min.js"></script>
<script src="/js/jquery.dropotron.min.js"></script>
<script src="/js/jquery.scrollex.min.js"></script>
<script src="/js/browser.min.js"></script>
<script src="/js/breakpoints.min.js"></script>
<script src="/js/util.js"></script>
<script src="/js/main.js"></script>
<script src="/js/myscripts.js"></script>
<script src="/lib/bootstrap/dist/js/bootstrap.js"></script>
<script src="/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>

@*     
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> *@